ALTER TABLE hr.`locations` CHANGE `STREET_ADDRESS` `ADDRESS` VARCHAR(40);

ALTER TABLE hr.`regions` CHANGE `REGION_NAME` `REGION` VARCHAR(25);

ALTER TABLE hr.`countries` CHANGE `COUNTRY_NAME` `COUNTRY` VARCHAR(40);
