CREATE DATABASE IF NOT EXISTS catalogo_albuns;

USE `catalogo_albuns`;

CREATE TABLE ARTISTAS(
	ARTISTA_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    SOBRENOME VARCHAR(20)
) ENGINE = InnoDB;

CREATE TABLE ESTILOS_MUSICAIS(
	ESTILO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ESTILO VARCHAR(50) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE ALBUNS(
	ALBUM_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_ALBUM VARCHAR(100) NOT NULL,
    ARTISTA_ID INT NOT NULL,
    ESTILO_ID INT NOT NULL,
    PRECO DOUBLE NOT NULL,
    ANO_LACAMENTO DATE,
    FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTAS(ARTISTA_ID),
    FOREIGN KEY (ESTILO_ID) REFERENCES ESTILOS_MUSICAIS(ESTILO_ID)
) ENGINE = InnoDB;

CREATE TABLE CANCOES(
	CANCOES_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_CANCAO VARCHAR(100) NOT NULL,
    ARTISTA_ID INT NOT NULL,
    ALBUM_ID INT NOT NULL,
	ESTILO_ID INT NOT NULL,
    ANO_LACAMENTO DATE,
    FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTAS(ARTISTA_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUNS(ALBUM_ID),
    FOREIGN KEY (ESTILO_ID) REFERENCES ESTILOS_MUSICAIS(ESTILO_ID)
) ENGINE = InnoDB;
    