CREATE DATABASE IF NOT EXISTS zoo_database;

USE `zoo_database`;

CREATE TABLE MANAGERS(
	MANAGER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE ANIMAL_KEEPER(
	KEEPER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    MANAGER_ID INT NOT NULL,
    FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS(MANAGER_ID)
) ENGINE = InnoDB;

CREATE TABLE SPECIES(
	SPECIES_ID INT PRIMARY KEY AUTO_INCREMENT,
    SPECIES_NAME VARCHAR(50) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE LOCATION(
	LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRY VARCHAR(20) NOT NULL,
    REGION VARCHAR(20) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE ANIMALS(
	ANIMAL_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    SPECIES_ID INT NOT NULL,
    GENDER CHAR(1) NOT NULL,
    AGE INT NOT NULL,
    LOCATION_ID INT NOT NULL,
    KEEPER_ID INT NOT NULL,
    FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES(SPECIES_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
    FOREIGN KEY (KEEPER_ID) REFERENCES ANIMAL_KEEPER(KEEPER_ID)
) ENGINE = InnoDB;
